services:
  postgres:
    image: postgres:18
    hostname: postgres
    restart: on-failure
    ports:
      - "15432:5432"
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vmemo_dev

  typesense:
    image: typesense/typesense:30.1
    hostname: typesense
    restart: on-failure
    ports:
      - "18108:8108"
    volumes:
      - ts-data:/data
    command: "--data-dir /data --api-key=xyz --enable-cors"

  postgres-test:
    image: postgres:18
    hostname: postgres-test
    restart: on-failure
    ports:
      - "25432:5432"
    volumes:
      - pg-test-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vmemo_test

  typesense-test:
    image: typesense/typesense:30.1
    hostname: typesense-test
    restart: on-failure
    ports:
      - "28108:8108"
    volumes:
      - ts-test-data:/data
    command: "--data-dir /data --api-key=xyz --enable-cors"

volumes:
  pg-data:
  pg-test-data:
  ts-data:
  ts-test-data:
