services:
  postgres:
    image: postgres:17
    restart: on-failure
    hostname: postgres
    ports:
      - "54321:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vmemo_dev

  postgres_test:
    image: postgres:17
    restart: on-failure
    hostname: postgres_test
    ports:
      - "54322:5432"
    volumes:
      - pg-test-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vmemo_test

  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    hostname: typesense
    ports:
      - "8766:8108"
    volumes:
      - ts-data:/data
    command: "--data-dir /data --api-key=xyz --enable-cors"

volumes:
  pg-data:
  pg-test-data:
  ts-data:
