import Config

config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
config :vmemo, Vmemo.AshRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "vmemo_dev",
  port: 54321,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :vmemo, typesense_url: "http://localhost:8766"
config :vmemo, typesense_api_key: "xyz"

config :vmemo, moondream_url: "http://m4-24:2020/v1"

# Admin token for development
config :vmemo, admin_token: "admin"

config :vmemo, Oban,
  repo: Vmemo.AshRepo,
  notifier: Oban.Notifiers.PG,
  plugins: [Oban.Plugins.Pruner],
  queues: [default: 10, sync_typesense: 5]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Store secret_key_base in application config for JWT signing
# JWT_SIGNING_SECRET is now merged with SECRET_KEY_BASE
config :vmemo, :secret_key_base, "m007g/tykiNHADOKiYRqEEHSTJpKMbBKzIkQMuDjyKLjVUlJA63WXda4DOeTfWNC"

config :vmemo, VmemoWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "m007g/tykiNHADOKiYRqEEHSTJpKMbBKzIkQMuDjyKLjVUlJA63WXda4DOeTfWNC",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:vmemo, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:vmemo, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :vmemo, VmemoWeb.Endpoint,
  reloadable_compilers: [:gettext, :elixir, :app],
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/vmemo_web/(controllers|live|components)/.*(ex|heex|js)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :vmemo, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true,
  # Enable debug attributes for Tidewave
  debug_attributes: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
