services:
  vmemo:
    platform: linux/amd64
    image: thaddeusjiang/vmemo:e2e
    command: ["start"]
    restart: on-failure
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TYPESENSE_URL: ${TYPESENSE_URL}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      OPENROUTER_API_KEY: "fake-key"
      MOONDREAM_URL: ""
      MOONDREAM_API_KEY: "fake-key"
      RESEND_API_KEY: "fake-key"
      SENTRY_DSN: https://public@example.com/1
      ADMIN_TOKEN: test-admin-password
      SECRET_KEY_BASE: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
      PHX_SERVER: "true"
      PHX_HOST: localhost
      PORT: "4000"
