defmodule Vmemo.AshRepo.Migrations.AddUsageCountToApiTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Only add usage_count to api_tokens if it doesn't exist
    execute("""
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'api_tokens' AND column_name = 'usage_count'
      ) THEN
        ALTER TABLE api_tokens ADD COLUMN usage_count bigint NOT NULL DEFAULT 0;
      END IF;
    END $$;
    """)
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'api_tokens' AND column_name = 'usage_count'
      ) THEN
        ALTER TABLE api_tokens DROP COLUMN usage_count;
      END IF;
    END $$;
    """)
  end
end
