defmodule Vmemo.Repo.Migrations.RebuildAllSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:photos_notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :photo_id, :uuid, null: false
      add :note_id, :uuid, null: false
    end

    create table(:photos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:photos_notes) do
      modify :photo_id,
             references(:photos,
               column: :id,
               name: "photos_notes_photo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:photos) do
      add :url, :text, null: false
      add :note, :text
      add :caption, :text
      add :ts_ocr, :text
      add :file_id, :text
      add :ash_user_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:photos_notes) do
      modify :note_id,
             references(:notes,
               column: :id,
               name: "photos_notes_note_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:notes) do
      add :text, :text, null: false
      add :ash_user_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:messages, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :text, :text, null: false
      add :tool_calls, {:array, :map}
      add :tool_results, {:array, :map}
      add :source, :text, null: false, default: "user"
      add :complete, :boolean, null: false, default: true
      add :conversation_id, :uuid, null: false
      add :response_to_id, :uuid
    end

    create table(:import_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :source_filename, :text
      add :metadata, :map
      add :result, :map
      add :error_message, :text
      add :import_zip_path, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :response_to_id,
             references(:messages,
               column: :id,
               name: "messages_response_to_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:conversations) do
      add :title, :text
      add :archived_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false
    end

    create table(:ash_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:conversations) do
      modify :user_id,
             references(:ash_users,
               column: :id,
               name: "conversations_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ash_users) do
      add :email, :text, null: false
      add :hashed_password, :text, null: false
      add :confirmed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_users, [:email], name: "ash_users_unique_email_index")

    create table(:ash_user_tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
      add :aud, :text
      add :exp, :utc_datetime
      add :iss, :text
      add :sub, :text
      add :typ, :text

      add :ash_user_id,
          references(:ash_users,
            column: :id,
            name: "ash_user_tokens_ash_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:api_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token_hash, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :expires_at, :utc_datetime
      add :last_used_at, :utc_datetime
      add :usage_count, :bigint, null: false, default: 0
      add :is_active, :boolean, default: true
      add :created_at, :utc_datetime, null: false

      add :ash_user_id,
          references(:ash_users,
            column: :id,
            name: "api_tokens_ash_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ai_vision_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :photo_id,
          references(:photos,
            column: :id,
            name: "ai_vision_requests_photo_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :ash_user_id,
          references(:ash_users,
            column: :id,
            name: "ai_vision_requests_ash_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :function_type, :text, null: false
      add :prompt, :text
      add :result, :map
      add :status, :text, null: false, default: "pending"
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:ai_vision_requests, "ai_vision_requests_photo_id_fkey")

    drop constraint(:ai_vision_requests, "ai_vision_requests_ash_user_id_fkey")

    drop table(:ai_vision_requests)

    drop constraint(:api_tokens, "api_tokens_ash_user_id_fkey")

    drop table(:api_tokens)

    drop constraint(:ash_user_tokens, "ash_user_tokens_ash_user_id_fkey")

    drop table(:ash_user_tokens)

    drop_if_exists unique_index(:ash_users, [:email], name: "ash_users_unique_email_index")

    alter table(:ash_users) do
      remove :updated_at
      remove :inserted_at
      remove :confirmed_at
      remove :hashed_password
      remove :email
    end

    drop constraint(:conversations, "conversations_user_id_fkey")

    alter table(:conversations) do
      modify :user_id, :uuid
    end

    drop table(:ash_users)

    alter table(:conversations) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :archived_at
      remove :title
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop constraint(:messages, "messages_response_to_id_fkey")

    alter table(:messages) do
      modify :response_to_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    drop table(:import_requests)

    drop table(:messages)

    alter table(:notes) do
      remove :updated_at
      remove :inserted_at
      remove :ash_user_id
      remove :text
    end

    drop constraint(:photos_notes, "photos_notes_note_id_fkey")

    alter table(:photos_notes) do
      modify :note_id, :uuid
    end

    drop table(:notes)

    alter table(:photos) do
      remove :updated_at
      remove :inserted_at
      remove :ash_user_id
      remove :file_id
      remove :ts_ocr
      remove :caption
      remove :note
      remove :url
    end

    drop constraint(:photos_notes, "photos_notes_photo_id_fkey")

    alter table(:photos_notes) do
      modify :photo_id, :uuid
    end

    drop table(:photos)

    drop table(:photos_notes)
  end
end
