defmodule Vmemo.Repo.Migrations.RebuildAllSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memo_notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :text, :text, null: false
      add :user_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:memo_images_notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :photo_id, :uuid, null: false
      add :note_id, :uuid, null: false
    end

    create table(:memo_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:memo_images_notes) do
      modify :photo_id,
             references(:memo_images,
               column: :id,
               name: "memo_images_notes_photo_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :note_id,
             references(:memo_notes,
               column: :id,
               name: "memo_images_notes_note_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:memo_images) do
      add :url, :text, null: false
      add :note, :text
      add :caption, :text
      add :ts_ocr, :text
      add :file_id, :text
      add :user_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:chat_messages, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :text, :text, null: false
      add :tool_calls, {:array, :map}
      add :tool_results, {:array, :map}
      add :source, :text, null: false, default: "user"
      add :complete, :boolean, null: false, default: true
      add :conversation_id, :uuid, null: false
      add :response_to_id, :uuid
    end

    create table(:chat_conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:chat_messages) do
      modify :conversation_id,
             references(:chat_conversations,
               column: :id,
               name: "chat_messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :response_to_id,
             references(:chat_messages,
               column: :id,
               name: "chat_messages_response_to_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:chat_conversations) do
      add :title, :text
      add :archived_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false
    end

    create table(:auth_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:chat_conversations) do
      modify :user_id,
             references(:auth_users,
               column: :id,
               name: "chat_conversations_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:auth_users) do
      add :email, :text, null: false
      add :hashed_password, :text, null: false
      add :confirmed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:auth_users, [:email], name: "auth_users_unique_email_index")

    create table(:auth_user_tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
      add :aud, :text
      add :exp, :utc_datetime
      add :iss, :text
      add :sub, :text
      add :typ, :text

      add :user_id,
          references(:auth_users,
            column: :id,
            name: "auth_user_tokens_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:auth_api_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token_hash, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :expires_at, :utc_datetime
      add :last_used_at, :utc_datetime
      add :usage_count, :bigint, null: false, default: 0
      add :is_active, :boolean, default: true
      add :created_at, :utc_datetime, null: false

      add :user_id,
          references(:auth_users,
            column: :id,
            name: "auth_api_tokens_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ai_vision_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :photo_id,
          references(:memo_images,
            column: :id,
            name: "ai_vision_requests_photo_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:auth_users,
            column: :id,
            name: "ai_vision_requests_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :function_type, :text, null: false
      add :prompt, :text
      add :result, :map
      add :status, :text, null: false, default: "pending"
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:ai_vision_requests, [:inserted_at])

    create index(:ai_vision_requests, [:status])

    create index(:ai_vision_requests, [:user_id])

    create index(:ai_vision_requests, [:photo_id])

    create table(:admin_import_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :source_filename, :text
      add :metadata, :map
      add :result, :map
      add :error_message, :text
      add :import_zip_path, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:admin_import_requests)

    drop constraint(:ai_vision_requests, "ai_vision_requests_photo_id_fkey")

    drop constraint(:ai_vision_requests, "ai_vision_requests_user_id_fkey")

    drop_if_exists index(:ai_vision_requests, [:photo_id])

    drop_if_exists index(:ai_vision_requests, [:user_id])

    drop_if_exists index(:ai_vision_requests, [:status])

    drop_if_exists index(:ai_vision_requests, [:inserted_at])

    drop table(:ai_vision_requests)

    drop constraint(:auth_api_tokens, "auth_api_tokens_user_id_fkey")

    drop table(:auth_api_tokens)

    drop constraint(:auth_user_tokens, "auth_user_tokens_user_id_fkey")

    drop table(:auth_user_tokens)

    drop_if_exists unique_index(:auth_users, [:email], name: "auth_users_unique_email_index")

    alter table(:auth_users) do
      remove :updated_at
      remove :inserted_at
      remove :confirmed_at
      remove :hashed_password
      remove :email
    end

    drop constraint(:chat_conversations, "chat_conversations_user_id_fkey")

    alter table(:chat_conversations) do
      modify :user_id, :uuid
    end

    drop table(:auth_users)

    alter table(:chat_conversations) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :archived_at
      remove :title
    end

    drop constraint(:chat_messages, "chat_messages_conversation_id_fkey")

    drop constraint(:chat_messages, "chat_messages_response_to_id_fkey")

    alter table(:chat_messages) do
      modify :response_to_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:chat_conversations)

    drop table(:chat_messages)

    alter table(:memo_images) do
      remove :updated_at
      remove :inserted_at
      remove :user_id
      remove :file_id
      remove :ts_ocr
      remove :caption
      remove :note
      remove :url
    end

    drop constraint(:memo_images_notes, "memo_images_notes_photo_id_fkey")

    drop constraint(:memo_images_notes, "memo_images_notes_note_id_fkey")

    alter table(:memo_images_notes) do
      modify :note_id, :uuid
      modify :photo_id, :uuid
    end

    drop table(:memo_images)

    drop table(:memo_images_notes)

    drop table(:memo_notes)
  end
end
