defmodule Vmemo.Repo.Migrations.VisionRequestIndexesAndUuidv7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:ai_vision_requests, [:inserted_at])

    create index(:ai_vision_requests, [:status])

    create index(:ai_vision_requests, [:ash_user_id])

    create index(:ai_vision_requests, [:photo_id])

    alter table(:ai_vision_requests) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end
  end

  def down do
    alter table(:ai_vision_requests) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    drop_if_exists index(:ai_vision_requests, [:photo_id])

    drop_if_exists index(:ai_vision_requests, [:ash_user_id])

    drop_if_exists index(:ai_vision_requests, [:status])

    drop_if_exists index(:ai_vision_requests, [:inserted_at])
  end
end
